### ISSUE TITLE
Build error with Firebase Analytics & Crashlytics

### ISSUE THREAD

**Issue by oguzydz** [relateddigital/react-native-related-digital#8]
### Description
When I want to use with Firebase Analytics & Crashlytics, there could be hermes compatible issue. Firsty, I added messaging and app libraries, I can handle with adding pod files manually.

> pod 'Firebase', :modular_headers => true
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true

However, with crashlytics and analytics I cannot find pod file which I can add manually to podfile.

### Build output

> SwiftEmitModule normal arm64 Emitting\ module\ for\ FirebaseSessions (in target 'FirebaseSessions' from project 'Pods')

**Libraries**

>  "@react-native-firebase/analytics": "^17.3.2",
    "@react-native-firebase/app": "^17.3.2",
    "@react-native-firebase/crashlytics": "^17.3.2", 
    "react-native-related-digital": "^1.0.7",

**System Info**

> System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 91.30 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 28, 29, 30, 31, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-26 | ARM 64 v8a, android-28 | Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play ARM 64 v8a, android-30 | ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by bariisarslans** [comment]
Hi,

We couldn't reproduce this issue in our local environment. Could it be a specific error related to your computer? If you have the opportunity to run the same project on a different computer, could you test it that way?
