### ISSUE TITLE
XCode Version 15.0 "Stored properties cannot be marked unavailable with '@available'" Problem

### ISSUE THREAD

**Issue by dogankablan** [relateddigital/react-native-related-digital#9]
Hi, I've upgraded Xcode to version 15.0, but I'm unable to build for iOS. The error message I'm receiving is:

/ios/Pods/VisilabsIOS/Sources/Utilities/Checkbox.swift:103:6 Stored properties cannot be marked unavailable with '@available'

How can I address this issue?

**Comment by bariisarslans** [comment]
Hi,

Which version are you using?
Can you send the contents of your Package.json file?

**Comment by dogankablan** [comment]
Hi, 

I use version 1.0.4

**Comment by bariisarslans** [comment]
This issue has been resolved in subsequent versions. Could you please update your version and try again?
